In [26]:
import numpy as np

In [53]:
a=np.mat(np.array([[1,2,3],[4,5,6],[7,8,9]]))

In [54]:
b=np.mat(np.array([[7,8,9],[10,11,12],[1,2,3]]))

In [55]:
#Q.1. Write a Python Program to Add Two Matrices?
c=a+b
print(f"Addition of two Matrices is")
print(c)

Addition of two Matrices is
[[ 8 10 12]
 [14 16 18]
 [ 8 10 12]]


In [56]:
#Q.2. Write a Python Program to Multiply Two Matrices?
c=a*b
print(f"Multiplication of two Matrices is")
print(c)

Multiplication of two Matrices is
[[ 30  36  42]
 [ 84  99 114]
 [138 162 186]]


In [59]:
#Q.print(numpy.transpose(matrix))
print("Normal matrix")
print(c)
print("After transpose")
print(np.transpose(c))
    

Normal matrix
[[ 30  36  42]
 [ 84  99 114]
 [138 162 186]]
After transpose
[[ 30  84 138]
 [ 36  99 162]
 [ 42 114 186]]


In [78]:
#Q.4. Write a Python Program to Sort Words in Alphabetic Order?
a=input("")
b=a.lower()
c=b.split()
c.sort()
print("after sorting new string look like")
print(*c)


this is a ineuron assignment
after sorting new string look like
a assignment ineuron is this


In [81]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = input("Enter a string: ")
no_punct = ""
for i in my_str:
    if i not in punctuations:
        no_punct = no_punct + i
print(no_punct)

Enter a string: hello!! Ineuron#
hello Ineuron
